name: clipboard_sync
description: A cross-platform clipboard synchronization application.

# SDK 版本约束
environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.19.4'

# 项目版本号
version: 1.0.0+1

# 依赖项
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0  # WebSocket 通信
  shared_preferences: ^2.2.0  # 本地存储
  clipboard: ^0.1.3           # 剪贴板操作
  device_info_plus: ^9.0.3    # 设备信息
  uuid: ^3.0.7                # 生成唯一 ID
  http: ^1.1.0                # HTTP 请求（可选，用于扩展功能）
  socket_io_client: ^2.0.0
  

# 开发依赖项
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0       # 代码静态分析工具

# Flutter 配置
flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/          # 静态资源目录（可选） 