name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # 运行你的测试命令，例如 pytest
        pytest

    - name: Package application
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: python-package
        path: dist/