# .github/workflows/build-and-package.yml
name: Build and Package Server and Client

on:
  push:
    branches: [ main ]

jobs:
  build-server-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: shnulaa/clipboard:latest

  build-flutter-android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable client/flutter
          echo "$(pwd)/client/flutter/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          cd client
          flutter pub get

      - name: Build Flutter Android APK
        run: |
          cd client
          flutter build apk --release